apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: starlane-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Starlane is the Schema for the starlanes API
      displayName: Starlane
      kind: Starlane
      name: starlanes.starlane.starlane.io
      version: v1alpha1
  description: Starlane Operator
  displayName: Starlane
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - resource mesh
  links:
  - name: Starlane Operator
    url: https://starlane-operator.domain
  maturity: alpha
  provider:
    name: starlane.io
    url: starlane.io
  version: 0.0.0
