apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:10.0.0


          ports:
            - name: keycloak
              containerPort: 8080
              protocol: TCP


          env:

          - name:  DB_VENDOR
            value: "postgres"
          - name:  DB_ADDR
            value: "postgres"
          - name:  DB_PORT 
            value: "5432"
          - name:  DB_USER
            value: "postgres"
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: PASSWORD 

          - name:  DB_DATABASE
            value: "postgres"
          - name:  KEYCLOAK_USER 
            value: "admin"
          - name:  KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: PASSWORD 

          - name: KEYCLOAK_CORS
            value: "true"
          - name: KEYCLOAK_ALWAYS_HTTPS
            value: "false"
          - name: PROTOCOL
            value: https
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"

