[package]
name = "starlane"
version = "0.1.0"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.4.0", features = ["full"] }
serde = { version="1.0.69", features=['derive','rc'] }
futures = "0.3.13"
log = "0.4.14"
async-trait = "0.1.48"
url = "2.2.1"
lru = "0.6.5"