[package]
name = "starlane"
version = "0.1.0"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2018"
description = "Starlane is a messaging framework built to faciliate realtime communication between the various components of a distributed application."
homepage = "http://starlane.io"
repository = "https://github.com/mechtronium/starlane"
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.4.0", features = ["full"] }
serde = { version="1.0.69", features=['derive','rc'] }
serde_json = "1.0"
futures = "0.3.13"
log = "0.4.14"
async-trait = "0.1.48"
url = "2.2.1"
lru = "0.6.5"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
#sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "sqlite" ] }
#sqlite = "0.26.0"
rusqlite = "0.25.3"
bincode = "1.3.3"
lazy_static = "1.4.0"
semver = "0.11.0"
base64 = "0.13.0"
