[package]
name = "starlane"
version = "0.1.0"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "starlane"

[dependencies]
starlane-core = { path = "../starlane-core" }
tokio = { version = "1.4.0", features = ["full"] }
clap = "2.33"
dirs = "3.0.2"
serde_json = "1.0"
serde = { version="1.0.69", features=['derive','rc'] }
lazy_static = "1.4.0"
