[package]
name = "mechtron-common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starlane-resources= { path = "../starlane-resources"}
serde = { version="1.0.69", features=['derive','rc'] }
