apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.26
          imagePullPolicy: Always

          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql
 
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP

          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "mysql-secrets"
                key: ROOT_PASSWORD


      volumes:
      - name: mysql
        persistentVolumeClaim:
         claimName: mysql-pvc


