# permissions for end users to view starlaneresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starlaneresource-viewer-role
rules:
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlaneresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlaneresources/status
  verbs:
  - get
