# permissions for end users to view starlanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starlane-viewer-role
rules:
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlanes/status
  verbs:
  - get
