# permissions for end users to edit starlanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starlane-editor-role
rules:
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlanes/status
  verbs:
  - get
