# permissions for end users to edit starlaneresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starlaneresource-editor-role
rules:
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlaneresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlaneresources/status
  verbs:
  - get
