# permissions for end users to edit starlaneprovisioners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starlaneprovisioner-editor-role
rules:
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlaneprovisioners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starlane.starlane.io
  resources:
  - starlaneprovisioners/status
  verbs:
  - get
