apiVersion: starlane.starlane.io/v1alpha1
kind: StarlaneResource
metadata:
  name: db-$INDEX
  ownerReferences:
  - apiVersion: starlane.starlane.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: StarlaneResource
    name: starlane
    uid: $STARLANE_UID

spec:
  snakeKey: "db_$INDEX"
  provisioner: mysql
  address: "hyperspace:core:database<Database>"
